### PR TITLE
Overhaul CI pipeline, test `symfony/*:^6` support, drop `symfony/*:<5.4` support, automate dependency upgrades

### PR DESCRIPTION
**Pull request by Ocramius**
This change is a major overhaul of the package as it currently is.

Current checklist of my targets:

 * [x] enabled github actions for `phpunit`
 * [x] enabled CS checks (will likely switch to `squizlabs/php_codesniffer` with a stricter standard)
 * [x] enabled static analysis checks (will likely switch to `vimeo/psalm`, since current checks are extremely superficial)
 * [x] testing `lowest` dependencies
 * [x] testing `locked` dependencies
 * [x] testing `highest` dependencies
 * [x] testing PHP 8.1
 * [x] dropping `symfony/*:<5.4` support
 * [x] support `symfony/*:^6`
 * [x] automated dependabot dependency upgrades (weekly, `widen` strategy, for now, although I endorse `bump`)
 * [x] reduced final distribution tarball (removed tests and build configurations from it) 

Pipeline runs visible at https://github.com/Ocramius/uuid-extra-bundle/actions, for now.

### CODE REVIEW

**Comment by Ocramius** [comment]
Following discussion with @mcfedr in https://github.com/ekreative/uuid-extra-bundle/pull/16#issuecomment-1003065332, I went a bit thermonuclear on this.

I suggest reviewing commit-by-commit.

In practice:

 * travis-ci is dead, so it had to be replaced: I went with a pipeline that I help maintaining, and which does the testing all-in-one
 * I restricted supported dependency ranges to what is practically possible to test right now: when PHP 8.2 is out, adding `~8.2.0` to `composer.json` should suffice
 * added more aggressive CS and static analysis checks

The above resulted in me finding a bunch of bugs due to incompatibilities between supported versions, so it was well worth investing the time to clean this up.

Since I basically went on and applied a lot of opinionated stuff, I am well aware that this may lead to some eye-rolling and be frowned upon, but it's done in good faith, and should hopefully simplify the maintenance of this package a bit (especially regarding new version support).

**Comment by mcfedr** [comment]
Wow, you really did a number on this!

> Since I basically went on and applied a lot of opinionated stuff, I am well aware that this may lead to some eye-rolling and be frowned upon, but it's done in good faith, and should hopefully simplify the maintenance of this package a bit (especially regarding new version support).

I'll be honest, did have some of that reaction, but i can appreciate these are valid choices, and i can see should make maintenance nice and easy, so looks good.

**Comment by mcfedr** [comment]
Just before I merge it - as i can see, looks like a lot of under hood chances, and drops older symfony/etc - so I'm thinking this should be fine to release as a semvar minor change - i dont see any functionality changes?

**Comment by Ocramius** [comment]
In theory, all of this is BC compliant, up to inheritance (due to added types for symfony 6 support).

It can be tagged as a minor, or as a major, if you want to be cautious, but the functionality is left intact.

**Pull request merged**
